# Generated by Django 2.2 on 2019-06-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post_pic',
            field=models.ImageField(blank=True, upload_to='postpic/%Y/%m/%d', verbose_name='post_pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='self_intro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='self_intro'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail', verbose_name='thumbnail'),
        ),
    ]
