# Generated by Django 2.2 on 2019-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20190629_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
